version: '3'

services:
  net.sds.healthcheck.host:
    image: net.sds.healthcheck.host
    build:
      context: ../../Net.SDS.HealthCheck/Net.SDS.HealthCheck.Host
      dockerfile: Dockerfile

  net.sds.registry.api:
    image: net.sds.registry.api
    build:
      context: ../../Net.SDS.Registry/Net.SDS.Registry.API
      dockerfile: Dockerfile
    ports:
     - "32789:80"

  sample.service.a:
    image: sample.service.a
    build:
      context: ../../Sample/Service.A
      dockerfile: Dockerfile
    ports:
     - "7001:80"
    depends_on:
      - "net.sds.registry.api"

  sample.service.b:
    image: sample.service.b
    build:
      context: ../../Sample/Service.B
      dockerfile: Dockerfile
    ports:
     - "7002:80"
    depends_on:
      - "net.sds.registry.api"

  sample.service.c:
    image: sample.service.c
    build:
      context: ../../Sample/Service.C
      dockerfile: Dockerfile
    ports:
     - "7003:80"
    depends_on:
      - "net.sds.registry.api"